default:
  @just --list --justfile "{{justfile()}}"

test-isolated:
    devenv test

test:
    judge

snapshot:
    judge -a

sample EX SAMPLE="":
    jpm -l janet "exercises/{{EX}}.janet" < "inputs/{{EX}}_sample{{SAMPLE}}"

solution EX:
    jpm -l janet "exercises/{{EX}}.janet" < "inputs/{{EX}}_solution"

repl EX:
    jpm -l janet -l "./exercises/{{EX}}"
